let Assets = [
  {
    name: "Potato",
    amount: 0,
    img_url: "",
    child: [
      {
        name: "Farmer",
        amount: 250,
        level: 1,
        outcome: 4,
        produce: "Parent",
        bro: "",
        time: 4,
        desc: "produce potatoes",
        cost: [
          {
            name: "Parent",
            quantity: 2,
          },
          {
            name: "Employee",
            quantity: 1,
          },
        ],
        bonus: {
          Power: {
            name: "POWER",
            quantity: 1,
            url_img: "",
          },
          Discount: {
            name: "DISCOUNT",
            quantity: 1,
            url_img: "",
          },
          Speed: {
            name: "SPEED",
            quantity: 1,
            url_img: "",
          },
          Chance: {
            name: "CHANCE",
            quantity: 1,
            url_img: "",
          },
          Bonus: {
            name: "BONUS",
            quantity: 2,
            url_img: "",
          },
        },
      },
      {
        name: "Commune",
        amount: 1,
        level: 1,
        outcome: 8,
        produce: "Farmer",
        bro: "",
        time: 8,
        desc: "produce Commune",
        cost: [
          {
            name: "Farmer",
            quantity: 2,
          },
          {
            name: "Employee",
            quantity: 1,
          },
        ],
        bonus: {
          Power: {
            name: "POWER",
            quantity: 1,
            url_img: "",
          },
          Discount: {
            name: "DISCOUNT",
            quantity: 1,
            url_img: "",
          },
          Speed: {
            name: "SPEED",
            quantity: 1,
            url_img: "",
          },
          Chance: {
            name: "CHANCE",
            quantity: 1,
            url_img: "",
          },
          Bonus: {
            name: "BONUS",
            quantity: 2,
            url_img: "",
          },
        },
      },
    ],
  },
  {
    name: "Orange",
    amount: 10,
    img_url: "",
    child: [
      {
        name: "Farmer",
        amount: 10,
        level: 1,
        outcome: 4,
        produce: "Parent",
        bro: "",
        time: 8,
        desc: "produce potatoes",
        cost: [
          {
            name: "Parent",
            quantity: 2,
          },
          {
            name: "Employee",
            quantity: 1,
          },
        ],
        bonus: {
          Power: {
            name: "POWER",
            quantity: 1,
            url_img: "",
          },
          Discount: {
            name: "DISCOUNT",
            quantity: 1,
            url_img: "",
          },
          Speed: {
            name: "SPEED",
            quantity: 1,
            url_img: "",
          },
          Chance: {
            name: "CHANCE",
            quantity: 1,
            url_img: "",
          },
          Bonus: {
            name: "BONUS",
            quantity: 2,
            url_img: "",
          },
        },
      },
      {
        name: "Commune",
        amount: 1,
        level: 1,
        outcome: 8,
        produce: "Farmer",
        bro: "",
        time: 8,
        desc: "produce Commune",
        cost: [
          {
            name: "Farmer",
            quantity: 2,
          },
          {
            name: "Employee",
            quantity: 1,
          },
        ],
        bonus: {
          Power: {
            name: "POWER",
            quantity: 1,
            url_img: "",
          },
          Discount: {
            name: "DISCOUNT",
            quantity: 1,
            url_img: "",
          },
          Speed: {
            name: "SPEED",
            quantity: 1,
            url_img: "",
          },
          Chance: {
            name: "CHANCE",
            quantity: 1,
            url_img: "",
          },
          Bonus: {
            name: "BONUS",
            quantity: 2,
            url_img: "",
          },
        },
      },
    ],
  },
  {
    name: "Tomato",
    amount: 100,
    img_url: "",
    child: [
      {
        name: "Farmer",
        amount: 15,
        level: 1,
        outcome: 4,
        produce: "Parent",
        bro: "",
        time: 16,
        desc: "produce potatoes",
        cost: [
          {
            name: "Parent",
            quantity: 2,
          },
          {
            name: "Employee",
            quantity: 1,
          },
        ],
        bonus: {
          Power: {
            name: "POWER",
            quantity: 1,
            url_img: "",
          },
          Discount: {
            name: "DISCOUNT",
            quantity: 1,
            url_img: "",
          },
          Speed: {
            name: "SPEED",
            quantity: 1,
            url_img: "",
          },
          Chance: {
            name: "CHANCE",
            quantity: 1,
            url_img: "",
          },
          Bonus: {
            name: "BONUS",
            quantity: 2,
            url_img: "",
          },
        },
      },
      {
        name: "Commune",
        amount: 1,
        level: 1,
        outcome: 8,
        produce: "Farmer",
        bro: "",
        time: 8,
        desc: "produce Commune",
        cost: [
          {
            name: "Farmer",
            quantity: 2,
          },
          {
            name: "Employee",
            quantity: 1,
          },
        ],
        bonus: {
          Power: {
            name: "POWER",
            quantity: 1,
            url_img: "",
          },
          Discount: {
            name: "DISCOUNT",
            quantity: 1,
            url_img: "",
          },
          Speed: {
            name: "SPEED",
            quantity: 1,
            url_img: "",
          },
          Chance: {
            name: "CHANCE",
            quantity: 1,
            url_img: "",
          },
          Bonus: {
            name: "BONUS",
            quantity: 2,
            url_img: "",
          },
        },
      },
    ],
  },
];
let Employee = {
  time: 4,
  amount: 10,
  produce_per_sec: 5,
};
let Cards = [
  {
    name: "card1",
    imgUrl: "",
    type: "Speed",
    related_assets: "Farmer",
    level_ratio: 2,
    level_require: 0,
    origin_ratio: 2,
    cost: 50,
    weight: 20,
  },
  {
    name: "card2",
    imgUrl: "",
    type: "Speed",
    related_assets: "Farmer",
    level_ratio: 2,
    level_require: 0,
    level: 0,
    origin_ratio: 2,
    cost: 50,
    has_amount: 0,
    weight: 20,
  },
  {
    name: "card3",
    imgUrl: "",
    type: "Speed",
    related_assets: "Farmer",
    level_ratio: 2,
    level_require: 0,
    level: 0,
    origin_ratio: 2,
    cost: 50,
    has_amount: 0,
    weight: 20,
  },
  {
    name: "card4",
    imgUrl: "",
    type: "Speed",
    related_assets: "Farmer",
    level_ratio: 2,
    level_require: 0,
    level: 0,
    origin_ratio: 2,
    cost: 50,
    has_amount: 0,
    weight: 20,
  },
  {
    name: "card5",
    imgUrl: "",
    type: "Speed",
    related_assets: "Farmer",
    level_ratio: 2,
    level_require: 0,
    level: 0,
    origin_ratio: 2,
    cost: 50,
    has_amount: 0,
    weight: 20,
  },
  {
    name: "card6",
    imgUrl: "",
    type: "Speed",
    related_assets: "Farmer",
    level_ratio: 2,
    level_require: 0,
    level: 0,
    origin_ratio: 2,
    cost: 50,
    has_amount: 0,
    weight: 20,
  },
  {
    name: "card7",
    imgUrl: "",
    type: "Speed",
    related_assets: "Farmer",
    level_ratio: 2,
    level_require: 0,
    level: 0,
    origin_ratio: 2,
    cost: 50,
    has_amount: 0,
    weight: 5,
  },
  {
    name: "card8",
    imgUrl: "",
    type: "Speed",
    related_assets: "Farmer",
    level_ratio: 2,
    level_require: 0,
    level: 0,
    origin_ratio: 2,
    cost: 50,
    has_amount: 0,
    weight: 10,
  },
  {
    name: "card9",
    imgUrl: "",
    type: "Speed",
    related_assets: "Farmer",
    level_ratio: 2,
    level_require: 0,
    level: 0,
    origin_ratio: 2,
    cost: 50,
    has_amount: 0,
    weight: 10,
  },
  {
    name: "card10",
    imgUrl: "",
    type: "Speed",
    related_assets: "Farmer",
    level_ratio: 2,
    level_require: 0,
    level: 0,
    origin_ratio: 2,
    cost: 50,
    has_amount: 0,
    weight: 1,
  },
  {
    name: "card11",
    imgUrl: "",
    type: "Speed",
    related_assets: "Farmer",
    level_ratio: 2,
    level_require: 0,
    level: 0,
    origin_ratio: 2,
    cost: 50,
    has_amount: 0,
    weight: 1,
  },
];
let Tasks = [
  {
    level: 0,
    config: [
      {
        desc: "拥有农民",
        type: "OWN",
        target_asset: "Farmer",
        target: 250,
        reward: { c_min: 10, c_max: 20, atLeast: 2, s_min: 100, s_max: 150 },
      },
      {
        desc: "收集土豆",
        type: "COLLECT",
        target_asset: "Potato",
        target: 25000,
        reward: { c_min: 10, c_max: 20, atLeast: 2, s_min: 100, s_max: 150 },
      },
      {
        desc: "收集卡片",
        type: "COLLECT",
        target_asset: "Card",
        target: 100,
        reward: { c_min: 10, c_max: 20, atLeast: 2, s_min: 100, s_max: 150 },
      },
      {
        desc: "花费点数",
        type: "SPEND",
        target_asset: "Science",
        target: 25,
        reward: { c_min: 10, c_max: 20, atLeast: 2, s_min: 100, s_max: 150 },
      },
    ],
  },
];
let Cards_Level_Target = [2, 5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000];
let Cards_Upgrade_Point = [
  50, 100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000,
];
export default {
  Assets,
  Employee,
  Tasks,
  Cards,
  Cards_Level_Target,
  Cards_Upgrade_Point,
};
